<?php
/**
 * test test test
 */

function gm_test_maps_menu() {
  $items = array();

  $items['gm_test_maps'] = array(
    'title' => 'TEST MAPS',
    'page callback' => 'gm_test_maps_test_maps',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function gm_test_maps_test_maps() {
  $output = gm_leaflet_render_map('example_map', 'gm_test_maps_1');

  return $output;
}
